# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipcard',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='remark'),
        ),
    ]
