# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customer_age'),
        ('consumer', '0004_auto_20160402_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.FloatField(verbose_name='hour')),
                ('category', models.CharField(choices=[('一般', '一般'), ('深層推拿', '深層推拿')], max_length=45, verbose_name='category')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
                ('MembershipCard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses_record', to='consumer.MembershipCard', verbose_name='membership card')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_record', to='user.Customer', verbose_name='customer')),
            ],
        ),
    ]
