# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0005_expensesrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensesrecord',
            options={'verbose_name': '消費資料', 'verbose_name_plural': '消費資料'},
        ),
        migrations.AlterField(
            model_name='membershipcard',
            name='number',
            field=models.IntegerField(default=1, unique=True, verbose_name='number'),
            preserve_default=False,
        ),
    ]
