# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0006_auto_20160402_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipcard',
            name='used_hour',
        ),
    ]
