# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0007_remove_membershipcard_used_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesrecord',
            name='money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
