# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0008_expensesrecord_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesrecord',
            old_name='money',
            new_name='price',
        ),
    ]
