# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0009_auto_20160402_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesrecord',
            old_name='MembershipCard',
            new_name='membership_card',
        ),
        migrations.AlterField(
            model_name='expensesrecord',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='price'),
        ),
    ]
