# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0009_auto_20160402_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='number')),
                ('massage_times', models.IntegerField(blank=True, null=True, verbose_name='massage times')),
                ('chief_complaint', models.TextField(blank=True, null=True, verbose_name='chief complaint')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='user.Customer')),
            ],
            options={
                'verbose_name': '主訴資料',
                'verbose_name_plural': '主訴資料',
            },
        ),
    ]
