# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0002_auto_20160402_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(blank=True, max_length=20, null=True, verbose_name='life focus')),
                ('physique', models.CharField(blank=True, max_length=20, null=True, verbose_name='physique')),
                ('sleep', models.CharField(blank=True, max_length=20, null=True, verbose_name='sleep quality')),
                ('diet', models.CharField(blank=True, max_length=20, null=True, verbose_name='diet')),
                ('excretion', models.CharField(blank=True, max_length=20, null=True, verbose_name='excretion')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='remark')),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle', to='medical_record.Complaint', verbose_name='complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Physique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='physique item')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('history', models.CharField(blank=True, max_length=20, null=True, verbose_name='history')),
                ('situation', models.CharField(blank=True, max_length=20, null=True, verbose_name='situation')),
                ('rehabilitation', models.CharField(blank=True, max_length=20, null=True, verbose_name='rehabilitation')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='remark')),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physique', to='medical_record.Complaint', verbose_name='physique')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='sport item')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='spot name')),
                ('frequency', models.CharField(blank=True, max_length=20, null=True, verbose_name='frequency')),
                ('time', models.CharField(blank=True, max_length=20, null=True, verbose_name='time')),
                ('history', models.CharField(blank=True, max_length=20, null=True, verbose_name='history')),
                ('review', models.CharField(blank=True, max_length=20, null=True, verbose_name='review')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='remark')),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='medical_record.Complaint', verbose_name='sport')),
            ],
        ),
    ]
