# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customer_age'),
        ('medical_record', '0003_lifestyle_physique_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage_times', models.IntegerField(blank=True, null=True, verbose_name='massage times')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='massage category')),
                ('hour', models.FloatField(verbose_name='hour')),
                ('skill', models.CharField(blank=True, max_length=20, null=True, verbose_name='massage skill')),
                ('feel', models.CharField(blank=True, max_length=20, null=True, verbose_name='massage feel')),
                ('felt', models.CharField(blank=True, max_length=20, null=True, verbose_name='massage felt')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='remark')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massage', to='user.Customer', verbose_name='customer')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massage', to='user.Master', verbose_name='master')),
            ],
        ),
        migrations.AlterField(
            model_name='physique',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='physique name'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='frequency time'),
        ),
    ]
