# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0004_auto_20160415_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massage',
            options={'verbose_name': '推拿資料', 'verbose_name_plural': '推拿資料'},
        ),
    ]
