# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 04:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_auto_20160331_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='name')),
                ('sex', models.CharField(blank=True, max_length=6, null=True, verbose_name='sex')),
                ('born', models.DateField(blank=True, null=True, verbose_name='born')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('cellphone', models.CharField(blank=True, max_length=20, null=True, verbose_name='cellphone')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '個人資料',
                'verbose_name_plural': '個人資料',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
