# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_auto_20160401_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='number')),
                ('name', models.CharField(max_length=45, verbose_name='name')),
                ('sex', models.CharField(blank=True, max_length=6, null=True, verbose_name='sex')),
                ('cellphone', models.CharField(blank=True, max_length=20, null=True, verbose_name='cellphone')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
