# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20160401_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='number')),
                ('massage_times', models.IntegerField(blank=True, null=True, verbose_name='massage times')),
                ('chief_complaint', models.TextField(blank=True, null=True, verbose_name='chief complaint')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='user.Customer')),
            ],
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': '師傅資料', 'verbose_name_plural': '師傅資料'},
        ),
    ]
