# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20160401_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
