# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='storage',
            field=models.IntegerField(blank=True, null=True, verbose_name='storage'),
        ),
    ]
