# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 08:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_customer_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='電話號碼必須是純數字，上限為15個字。例如+8861234567,021234567', regex='^\\+?\\d{5,15}$')], verbose_name='電話號碼')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customerphone',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='user.Customer'),
        ),
    ]
