# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 07:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20160512_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerphone',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='user.Customer'),
        ),
        migrations.AlterField(
            model_name='customerphone',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='電話號碼必須是純數字，上限為15個字。例如+8861234567,021234567', regex='^\\+?\\d{5,15}$')], verbose_name='電話號碼'),
        ),
    ]
