# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_customer_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('hour', models.FloatField(choices=[(0.5, 0.5), (1, 1), (1.5, 1.5), (2.0, 2.0)], verbose_name='hour')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='massage category')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='remark')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='user.Customer', verbose_name='customer')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='user.Master', verbose_name='master')),
            ],
        ),
    ]
