# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_phonerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonerecord',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='電話時間'),
        ),
    ]
